/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#b6c4ff",
        "on-secondary-fixed-variant": "#653e00",
        error: "#ba1a1a",
        "secondary-container": "#fea619",
        tertiary: "#00312c",
        "tertiary-fixed": "#89f5e7",
        "outline-variant": "#c5c5d3",
        "inverse-on-surface": "#eff1f3",
        "surface-container": "#eceef0",
        "on-secondary-container": "#684000",
        "surface-container-high": "#e6e8ea",
        "tertiary-fixed-dim": "#6bd8cb",
        "secondary-fixed-dim": "#ffb95f",
        "surface-tint": "#4059aa",
        "surface-container-low": "#f2f4f6",
        "surface-container-lowest": "#ffffff",
        "secondary": "#855300",
        "on-secondary-fixed": "#2a1700",
        "inverse-surface": "#2d3133",
        surface: "#f7f9fb",
        "primary-container": "#1e3a8a",
        "on-surface-variant": "#444651",
        "on-secondary": "#ffffff",
        outline: "#757682",
        "surface-dim": "#d8dadc",
        "on-error": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-container": "#4ebdb0",
        "on-primary": "#ffffff",
        "secondary-fixed": "#ffddb8",
        "inverse-primary": "#b6c4ff",
        "on-surface": "#191c1e",
        "on-tertiary-fixed": "#00201d",
        "on-tertiary-fixed-variant": "#005049",
        "tertiary-container": "#004942",
        "on-primary-fixed-variant": "#264191",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        primary: "#00236f",
        "primary-fixed": "#dce1ff",
        "surface-variant": "#e0e3e5",
        "on-primary-container": "#90a8ff",
        "on-background": "#191c1e",
        background: "#f7f9fb",
        "on-primary-fixed": "#00164e",
        "surface-bright": "#f7f9fb",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-max-width": "1280px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "24px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        "title-md": ["Inter"],
        "label-md": ["Inter"],
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Inter"],
      },
      fontSize: {
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};
